version: '3.2'
services:
    postgres:
      image: postgres:10.5
      restart: always
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data/:/var/lib/postgresql/data/
        - ./create.sql:/docker-entrypoint-initdb.d/create.sql
